name: arr_stack

include:
  # Main Arrs; Comment out to disable
  - main_arrs/lidarr.yml
  - main_arrs/radarr.yml
  - main_arrs/readarr.yml
  - main_arrs/sonarr.yml

  # Download Client/VPN; Comment out to disable
  - download_client_vpn/qbittorrent.yml
  - download_client_vpn/gluetun.yml

  # Management; Comment out to disable
  - management/overseer.yml
  - management/flaresolverr.yml
  - management/prowlarr.yml
  - management/profilarr.yml