name: arr_stack

include:
  # Main Arrs; Comment out to disable
  - main_arrs/lidarr.yml
  - main_arrs/radarr.yml
  # - main_arrs/readarr.yml # Buggy, disabled for now
  - main_arrs/sonarr.yml

  # Download Client/VPN; Comment out to disable
  - download_client_vpn/qbittorrent.yml
  - download_client_vpn/gluetun.yml
  - download_client_vpn/calibre-web-automated-book-downloader.yml

  # Management; Comment out to disable
  - management/flaresolverr.yml
  - management/prowlarr.yml
  - management/profilarr.yml
  - management/huntarr.yml

  # User Facing; Comment out to disable
  - user-facing/calibre-web-automated.yml
  - user-facing/overseerr.yml

networks:
  arr_stack_default:
    name: arr_stack_default
    external: true # Temporary for use of a manually configured ipv6 network