services:
  cleanuparr:
    image: ghcr.io/cleanuparr/cleanuparr:latest
    container_name: cleanuparr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PORT=11011
    volumes:
      - cleanuparr_config:/config
    ports:
      - 11011:11011
    restart: unless-stopped
volumes:
  prowlarr_config: