services:
  overseerr:
    image: linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - LOG_LEVEL=info
      - PORT=5055
    ports:
      - 5055:5055
    volumes:
      - overseerr_config:/config
    restart: unless-stopped
volumes:
  overseerr_config: