services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - sonarr_config:/config
      - ${DOWNLOADS_PATH}:/media/downloads
      - ${TV_PATH}:/media/movies
      - ${OLD_TV_PATH}:/media/old_movies
    ports:
      - 8989:8989
    restart: unless-stopped
volumes:
  sonarr_config: